### ISSUE TITLE
Option to customize the Cards value

### ISSUE THREAD

**Issue by loehard** [cschleiden/azure-boards-estimate#73] opened 2019-07-04 13:34 UTC
Hi! 
Is there any chances to add the option to customize the Cards values again? 

If I remember correctly, this option was available in V1.

![Cards option](https://user-images.githubusercontent.com/11324159/60670438-feb9ce80-9e46-11e9-90b2-cc23d891cd89.png)

Thank you.

**Comment by cschleiden** [comment] 2019-07-09 02:53
Version 1 had even fewer card sets. What are you looking for?

**Comment by cschleiden** [comment] 2019-07-09 02:53
Dupe of #5

**Closed by cschleiden** 2019-07-09 02:53 UTC
Labels: feature-request

**Comment by loehard** [comment] 2019-07-11 13:33
> Version 1 had even fewer card sets. What are you looking for?

Hi Chris!
Version 1 had the option to use the 0.5 which is missing now. 
0, 0.5, 1, 2, 3, 5, 8, 13, 20, 40, 100, “?”, "∞" and Coffee
