### ISSUE TITLE
V2 missed feature : start estimate from a selection of work items

### ISSUE THREAD

**Issue by RafaelKoch** [cschleiden/azure-boards-estimate#19] opened 2019-04-01 13:16 UTC
Hi,

In V2 I can not start an estimate session from a selection of work items (from a query). I do not know if this is related to the very old #2 ? 

Anyway, if this is a duplicate -  sorry!

**Comment by cschleiden** [comment] 2019-04-02 03:42
Duplicate of #23

**Closed by cschleiden** 2019-04-02 03:42 UTC
