### ISSUE TITLE
Roll back to v1?

### ISSUE THREAD

**Issue by jtrout** [cschleiden/azure-boards-estimate#72] opened 2019-07-03 20:19 UTC
Is there any way to roll back to v1? v2 looks great, but there are far too many bugs, and it's really frustrating our team.

**Comment by cschleiden** [comment] 2019-07-03 20:23
No, that is not possible. What problems are you encountering?

**Comment by jtrout** [comment] 2019-07-03 20:32
- Anyone in the team can click any story and change the view for everyone (removing the votes, as well).
- Anyone in the estimating session can submit a vote
- There's no clear way to accept an average of votes anymore
- There's no longer a way to enter an override value for the estimation amount
- Anyone can close the session/see the admin buttons
- Anyone can reveal the vote or submit a bid
- Auto-update doesn't seem to work properly (everyone sees a completely different list of what users are logged into the session, numbers don't update for everyone when a bid is accepted on the story card, new sessions don't pop in on the sessions page without refreshing)
- It doesn't seem to be possible to see who was responsible for which vote
- Shading is strange in the story description (particularly for users using the dark theme) making a lot of the content difficult to read

**Comment by jtrout** [comment] 2019-07-03 20:33
Don't misunderstand, we couldn't live without this plugin, and we love it. And the UI refresh and integration are fantastic, I really appreciate your efforts. We just are struggling with the new version a bit :)

**Comment by cschleiden** [comment] 2019-07-03 21:09
I appreciate the feedback, I can work much better with concrete issues :)

> * Anyone in the team can click any story and change the view for everyone (removing the votes, as well).
> * Anyone in the estimating session can submit a vote

That has always been the case, though. I want to keep it simple and have always operated with the assumption that teams use some other means of communication during an estimation session like a Teams/Zoom/... call. 

> * There's no clear way to accept an average of votes anymore
> * There's no longer a way to enter an override value for the estimation amount **_(I'm wrong here, there is an "enter a custom value" option)_**

Yep, the value in the textbox should be accepted. 

> * Anyone can close the session/see the admin buttons
> * Anyone can reveal the vote or submit a bid

That is by design. In the past this has led to a lot of frustration where users created sessions, didn't end them, and then left the company, or went on vacation, or were not available for other reasons. I tried to remove that friction point.

> * Auto-update doesn't seem to work properly (everyone sees a completely different list of what users are logged into the session, 

This sounds like a bug, can you file an issue please?

> numbers don't update for everyone when a bid is accepted on the story card, 

That was a bug that was fixed last week. Do you still see this?

>new sessions don't pop in on the sessions page without refreshing)

That's correct, no live reload for that for now. But V1 also didn't do that, so that wouldn't help. Feel free to create a suggestion issue for this.

> * It doesn't seem to be possible to see who was responsible for which vote

Do you mean this?
![image](https://user-images.githubusercontent.com/2201819/60625247-0bcdb380-9d9c-11e9-8fed-903c42d690dc.png)

> * Shading is strange in the story description (particularly for users using the dark theme) making a lot of the content difficult to read

Can you provide a screenshot? And please file a separate issue, this sounds like a bug.

**Comment by cbuchanan** [comment] 2019-07-10 17:43
> > * Anyone in the team can click any story and change the view for everyone (removing the votes, as well).
> 
> That has always been the case, though. I want to keep it simple and have always operated with the assumption that teams use some other means of communication during an estimation session like a Teams/Zoom/... call.

I don't believe that to be true - I would routinely move around the list in my own browser without affecting the team (and what people see in the Zoom session). Now it's really easy for anyone to screw up the current session.

> > * There's no clear way to accept an average of votes anymore
> > * There's no longer a way to enter an override value for the estimation amount **_(I'm wrong here, there is an "enter a custom value" option)_**
> 
> Yep, the value in the textbox should be accepted.

The loss of averages is unfortunate not but critical. The value in the textbox though should be defaulted with something.

> > * Anyone can close the session/see the admin buttons
> > * Anyone can reveal the vote or submit a bid
> 
> That is by design. In the past this has led to a lot of frustration where users created sessions, didn't end them, and then left the company, or went on vacation, or were not available for other reasons. I tried to remove that friction point.

With respect, I believe that's a bad design choice. I understand that there was a problem with hanging sessions, but now we have a problem where everyone is an admin and we're having all sorts of problems with people ending the bidding on a particular item prematurely. I think that allowing the DevOps projects admins to delete a hanging session would be a better approach to resolving the issue instead of letting anyone in the session accidentally hijack it.


> > * It doesn't seem to be possible to see who was responsible for which vote
> 
> Do you mean this?
> ![image](https://user-images.githubusercontent.com/2201819/60625247-0bcdb380-9d9c-11e9-8fed-903c42d690dc.png)

It's harder to tell now. The other thing is that with v1 we could see whose votes were still outstanding, and now we can't.

I'm definitely a fan of a number of the improvements, but some of the changes are causing a real issue. TBH my team would rather use v1 because of the challenges that have been outlined above, but obviously tweaking the functionality in v2 would be better.

**Comment by cschleiden** [comment] 2019-07-10 19:04
That's interesting: 
> The other thing is that with v1 we could see whose votes were still outstanding, and now we can't.

Created #75 to track

**Comment by rabotond** [comment] 2019-07-12 11:04
Many teams in the company I work for miss the average results. I would say if there are just a few member in the estimate session by looking on the values you can say what is the average but as we are most of the time more then 10 in the estimate it can be hard to average it. If that could be added back we would really appreciate it.

**Comment by cschleiden** [comment] 2019-07-12 15:39
@rabotond Feel free to upvote here: https://github.com/cschleiden/azure-boards-estimate/issues/37

**Comment by TWilbornArch** [comment] 2019-07-12 19:30
The point here - "Anyone in the team can click any story and change the view for everyone (removing the votes, as well)." I second that this has changed and it causing problems for my team. Can we get this changed so that there is a "Session Admin" that can control the primary story to be voted on?

**Comment by KyleKorndoerfer** [comment] 2019-07-18 14:24
I will add that our team is also experiencing many of the issues stated above, particularly around other users being able to switch work items being reviewed which removes the current votes. This has happened numerous times in our estimation sessions since this was released.

We love using this extension and are generally liking the new version, but this is our biggest pain point currently. I'll also second the ability to prevent everyone from administering the sessions as well. Should be limited to a smaller group (project admins and/or the person who created the session).

**Comment by shahhirenv** [comment] 2019-08-20 02:27
We recently upgraded to V2 in our organization and have the exact same issues mentioned in this post. Like everyone else, bullet #1 "Anyone in the team can click any story and change the view for everyone (removing the votes, as well)." has caused lot of frustration on my team since sometimes upon removing votes the teams have to vote multiple times. Even though I absolutely loved V2, this is one feature that is going to be a deal breaker for me to use other tools vs this one.

**Comment by cschleiden** [comment] 2019-08-28 21:46
Closing in favor of #63

**Closed by cschleiden** 2019-08-28 21:46 UTC
Labels: question
