### ISSUE TITLE
Unable to create session (work item context, query or sprint)

### ISSUE THREAD

**Issue by benbalki** [cschleiden/azure-boards-estimate#80] opened 2019-07-24 20:17 UTC
I've installed the extension on Azure DevOps server 2019 (version 2019.0.1).
I was able to install the extension but unable to create any session using all of the option (query, sprint or from the work item context.
![image](https://user-images.githubusercontent.com/46313617/61787433-6f398700-ae18-11e9-978c-ac968250cc42.png)
When clicking the Create button nothing happens.
another issue is that the setting tab in not working
![image](https://user-images.githubusercontent.com/46313617/61787637-dbb48600-ae18-11e9-87c3-500ef9762297.png)
Please assist,

**Comment by cschleiden** [comment] 2019-07-24 20:47
Any console errors?

**Comment by scottlezberg** [comment] 2019-07-25 05:21
This is the same issue I am having - https://github.com/cschleiden/azure-boards-estimate/issues/68

**Comment by benbalki** [comment] 2019-07-25 07:27
The console consist with the same errors as in #68.

**Comment by arvindsedha** [comment] 2019-07-30 11:28
I am having same problem with On-Premises DevOps 2019. Waiting for a fix !!

**Comment by cschleiden** [comment] 2019-07-30 16:22
Duplicate of #68

**Closed by cschleiden** 2019-07-30 16:22 UTC
