### ISSUE TITLE
Cannot install on Azure DevOps Server 2019

### ISSUE THREAD

**Issue by pascalberger** [cschleiden/azure-boards-estimate#65] opened 2019-06-18 07:32 UTC
While the extensions says "Azure DevOps Server 2019" under "Works with" it still cannot be installed with the following message below the "Install" button: 

> This extension does not support the version of the Server you are currently using. See Works With for supported Server versions.

Installed version is Azure DevOps Server 2019.0.1

**Comment by cschleiden** [comment] 2019-07-03 21:28
Could you try again? I just installed it successfully on an Azure DevOps Server 2019 - Update 1 RC server.

**Comment by cschleiden** [comment] 2019-08-29 17:57
Duplicate of #68

**Closed by cschleiden** 2019-08-29 17:57 UTC
Labels: bug
